version : "3.3"
services:
  api-preauthorization:
      build:
        context: "."
      environment:
        entity_id: 8ac7a4ca6db97ef1016dbe9214e70aac
        Authentication: OGFjN2E0Y2E2ZGI5N2VmMTAxNmRiZTkwZTMxZDBhYTh8WENkRUs0NHJubQ==
        # dockerfile: "" If we changed Dockerfile name we can put it here in this line
      container_name: preauthorization-container
      restart: always
      ports:
          - "8888:8888"
